# Generated by Django 5.1.6 on 2025-02-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blacklistedstreamer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('twitter', 'Twitter'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='accounts.streamer')),
            ],
        ),
    ]
