# Generated by Django 5.1.6 on 2025-02-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('PR', 'Présentiel'), ('DI', 'Distanciel')], max_length=2)),
                ('nombre_de_postes', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=150)),
                ('pseudo_discord', models.CharField(blank=True, max_length=150)),
                ('pseudo_twitch', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('pourquoi', models.TextField(verbose_name='Pourquoi je veux rejoindre le staff')),
                ('status', models.CharField(choices=[('candidature', 'Candidature'), ('staff', 'Staff effectif'), ('reserve', 'Réserve')], default='candidature', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_applications', to='accounts.streamer')),
                ('tags', models.ManyToManyField(blank=True, to='accounts.tag')),
                ('poste_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.staffposition')),
            ],
        ),
    ]
