# Generated by Django 5.1.6 on 2025-02-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffposition_staffapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='Serveur SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Port SMTP')),
                ('username', models.CharField(max_length=255, verbose_name="Nom d'utilisateur")),
                ('password', models.CharField(max_length=255, verbose_name='Mot de passe')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Utiliser SSL')),
            ],
        ),
    ]
