# Generated by Django 5.1.5 on 2025-01-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='broadcaster_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='streamer',
            name='follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streamer',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
