# Generated by Django 5.1.5 on 2025-01-18 22:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_streamer_broadcaster_type_streamer_follower_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='social_links',
        ),
        migrations.AddField(
            model_name='streamer',
            name='discord',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamer',
            name='presence_mode',
            field=models.CharField(choices=[('PR', 'Présentiel'), ('DI', 'Distanciel')], default='DI', max_length=2),
        ),
        migrations.AddField(
            model_name='streamer',
            name='validated_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('twitter', 'Twitter'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='main_app.streamer')),
            ],
        ),
    ]
