# Generated by Django 5.1.6 on 2025-02-08 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACLRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('twitch_wall', 'Twitch Wall'), ('smtp_config', 'Configuration SMTP'), ('admin_dashboard', 'Dashboard Admin')], max_length=50, verbose_name='Ressource')),
                ('action', models.CharField(choices=[('view', 'Afficher'), ('edit', 'Modifier'), ('delete', 'Supprimer')], max_length=50, verbose_name='Action')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Groupe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'unique_together': {('group', 'user', 'resource', 'action')},
            },
        ),
    ]
